server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vikingar_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
#  devtools:
#    restart:
#      # 开启热部署（更改文件后，自动重启）
#      enabled: true
#      ## 设置哪些资源变动后不触发热部署，会覆盖默认的exclude内容（资源不会触发重启，但会触发实时重新加载）
#      # exclude: WEB-INF/**,static/**
#      ## 监控额外的路径（优先于exclude）
#      # additional-paths: src/main/java
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: 0j97elK5dqkzXAYqJ-KSoltpG90XOZb7jvveFjxC
  secretKey: DnUPO0u6SGmKTSYEz9yo2gitC7ByOoskZfZi9vMK
  bucket: vikingar